# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7dff869961b70357e211518ce7954d8f2056cb1f2f54dfe1904dab847a119b3e19b117cce4bc105453775056b89993130c12e89f7af05e3b0505f86ef9e1a86

test:
  secret_key_base: 67180c9cba01deb5a8f1fe04378c3cf004f6b3c4e7a225b132cfd9ae187faa2c8c0d876ced7f7b36d183181ad67025b15016ec50b49a5edaef74726a767180ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
